import { existsSync, readFileSync } from 'fs';
import { join } from 'path';
import { Finding } from '../shared/types';

export interface PackageVersion {
  name: string;
  version: string;
}

/**
 * Parses an npm package-lock.json (lockfile v2/v3 format, generated by
 * npm 7+) and extracts every resolved package name + exact version.
 *
 * We deliberately read the LOCKFILE rather than package.json, because
 * package.json only has version RANGES ("^4.21.0"), not the exact
 * version actually installed. A vulnerability scan against a range is
 * meaningless — two developers running `npm install` on the same
 * package.json can end up with different resolved versions.
 *
 * This is a pure function (no I/O), which makes it unit-testable without
 * needing a real project on disk.
 */
export function parseLockfileDependencies(lockfileContent: string): PackageVersion[] {
  const lockfile = JSON.parse(lockfileContent);
  const results: PackageVersion[] = [];

  // npm lockfile v2/v3: dependencies live under "packages", keyed by
  // path like "node_modules/express". The root project itself is the
  // key "" and should be skipped.
  if (lockfile.packages && typeof lockfile.packages === 'object') {
    for (const [pkgPath, meta] of Object.entries(lockfile.packages)) {
      if (pkgPath === '' || !pkgPath.includes('node_modules/')) continue;
      const name = pkgPath.substring(pkgPath.lastIndexOf('node_modules/') + 'node_modules/'.length);
      const version = (meta as { version?: string }).version;
      if (name && version) {
        results.push({ name, version });
      }
    }
    return dedupe(results);
  }

  // Fallback: older npm lockfile v1 format, keyed by "dependencies".
  if (lockfile.dependencies && typeof lockfile.dependencies === 'object') {
    for (const [name, meta] of Object.entries(lockfile.dependencies)) {
      const version = (meta as { version?: string }).version;
      if (name && version) {
        results.push({ name, version });
      }
    }
    return dedupe(results);
  }

  return results;
}

function dedupe(pkgs: PackageVersion[]): PackageVersion[] {
  const seen = new Set<string>();
  const result: PackageVersion[] = [];
  for (const pkg of pkgs) {
    const key = `${pkg.name}@${pkg.version}`;
    if (!seen.has(key)) {
      seen.add(key);
      result.push(pkg);
    }
  }
  return result;
}

interface OsvBatchQuery {
  package: { name: string; ecosystem: 'npm' };
  version: string;
}

interface OsvVulnId {
  id: string;
  summary?: string;
}

interface OsvBatchResponseEntry {
  vulns?: OsvVulnId[];
}

/**
 * Queries the OSV.dev API (Google's Open Source Vulnerabilities
 * database, the same data source npm/GitHub advisories pull from) in a
 * single batched request for every dependency, instead of one HTTP call
 * per package. This is the same approach `npm audit` uses conceptually,
 * but implemented from scratch here to demonstrate understanding of how
 * vulnerability scanning actually works, not just calling `npm audit`
 * as a subprocess.
 */
export async function checkDependencies(projectPath: string): Promise<Finding[]> {
  const lockfilePath = join(projectPath, 'package-lock.json');

  if (!existsSync(lockfilePath)) {
    throw new Error(
      'No package-lock.json found. Run `npm install` in the target project first.'
    );
  }

  const packages = parseLockfileDependencies(readFileSync(lockfilePath, 'utf-8'));

  if (packages.length === 0) {
    return [];
  }

  const queries: OsvBatchQuery[] = packages.map((pkg) => ({
    package: { name: pkg.name, ecosystem: 'npm' },
    version: pkg.version,
  }));

  const response = await fetch('https://api.osv.dev/v1/querybatch', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ queries }),
  });

  if (!response.ok) {
    throw new Error(`OSV API request failed with status ${response.status}`);
  }

  const body = (await response.json()) as { results: OsvBatchResponseEntry[] };

  const findings: Finding[] = [];

  body.results.forEach((entry, index) => {
    const pkg = packages[index];
    for (const vuln of entry.vulns ?? []) {
      findings.push({
        source: 'dependencies',
        severity: 'high', // OSV batch endpoint doesn't return severity; treated conservatively
        title: `Vulnerable dependency: ${pkg.name}@${pkg.version}`,
        detail: `${vuln.id}${vuln.summary ? ' — ' + vuln.summary : ''}`,
        recommendation: `Run \`npm audit\` or check https://osv.dev/vulnerability/${vuln.id} for a fixed version`,
      });
    }
  });

  return findings;
}
